### ISSUE TITLE
Use React Router to Add A Header Component That Routes To Home, Playlists, and Quiz.

### ISSUE THREAD

**Issue by LNA** [some-lab/glow#8]
## Description
- [x] Add a Header component.
- [x] Use React Router to route to `/` (home), `/playlists`, and `/quiz` inside the component.
- [x] Manually test that each route works.
- [x] At `/`, We should see something like "Welcome To Glow" on the home page.
- [x] At `playlists`, we should see all of the playlists.
- [x] At `quiz`, we should something like "Coming Soon".

## Resources
If you've not worked in React Router before, that's fine! This project is here to give you the opportunity to learn new things.  
1. https://medium.com/@pshrmn/a-simple-react-router-v4-tutorial-7f23ff27adf

**Comment by karuna24s** [comment]
I will work on this.
